project_id = "mxqukplimaeilkpvihpr"

[functions.freedompay-create-payment]
verify_jwt = true

[functions.freedompay-callback]
verify_jwt = false

[functions.send-activation-reminder]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.send-system-notification]
verify_jwt = true

[functions.ban-user]
verify_jwt = true

[functions.reset-personal-activations]
verify_jwt = false